// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xebupzloagkebadwwewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlYnVwemxvYWdrZWJhZHd3ZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzUxMjQsImV4cCI6MjA2MTMxMTEyNH0.lkaoWZROaAgCbDufzXP1NqrGGgoQPXRy1auOkaK62-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);